name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create-tag.outputs.version }}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: create-tag
        id: create-tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
  draft-release:
    needs: create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{needs.create-tag.outputs.output1}}
          # version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{needs.create-tag.outputs.output1}}
          name: Release ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          # prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: true
          allowUpdates: true
          artifacts: "*,src/*"
          token: ${{ secrets.GITHUB_TOKEN }}
